using Contracts.Application.Handlers.DocumentHandler.Commands.UpdateDocument;

namespace Contracts.Application.Handlers.ContractDocHandler.Commands.UpdateContractDoc;

public class UpdateContractDocCommandValidator : UpdateDocumentCommandValidator;
