using Contracts.Application.Handlers.DocumentHandler.Commands.DownloadDocument;

namespace Contracts.Application.Handlers.ContractDocHandler.Commands.DownloadContractDoc;

public class DownloadContractDocCommandValidator : DownloadDocumentCommandValidator;
