version: '3.4'

services:
  contracts.api:
    image: ${DOCKER_REGISTRY-}contractsapi
    build:
      context: .
      dockerfile: Contracts.Api\Dockerfile

  sql_server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "0bd7903b-f568-4894-8d72-3c1b507e5644"
    ports: 
      - "1433:1433"

  nginx_proxy:
    container_name: proxy_container
    image: nginx:mainline
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    ports:
      - "80:80"
